# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a73b0c6107fb425bd4fe60829f87b3d590b1b3573c404eeea1fbbbdde7710c4b5c712550eb371c2793232d16a61594ee036c3a4f24df4234c5ca84df7c5f58e7

test:
  secret_key_base: 8d49da1440f5c84c44f6b1e4cd3b9734439e64e714e3f59ae417f59886f5e6ec198e087659aea3fefe8a0a0ce30ad4106b674ffcd3e54ad2fc76710a718d88e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
